# Generated by Django 3.1.14 on 2023-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('bond_name', models.CharField(max_length=255)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_interest_rateByRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('commodity_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('currency_pair', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FedRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('fed_name', models.CharField(max_length=255)),
                ('fedRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_fedRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_fedRateByRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GdpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('country_name', models.CharField(max_length=255)),
                ('gdp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_gdp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('index_name', models.CharField(max_length=255)),
                ('index_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('index_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
